// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BYBYSCREEN_H
#define UI_BYBYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_bybyScreen
extern void ui_bybyScreen_screen_init(void);
extern void ui_bybyScreen_screen_destroy(void);
extern void ui_event_bybyScreen(lv_event_t * e);
extern lv_obj_t * ui_bybyScreen;
extern void ui_event_bybyButton5(lv_event_t * e);
extern lv_obj_t * ui_bybyButton5;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_bybyPanel5;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

