// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_bybyScreen = NULL;
lv_obj_t * ui_bybyButton5 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_bybyPanel5 = NULL;
lv_obj_t * ui_Label23 = NULL;
// event funtions
void ui_event_bybyScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_TScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TScreen_screen_init);
    }
}
//这里链接关机的函数shutdown
void ui_event_bybyButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Shutdown(e);
    }
}

// build funtions

void ui_bybyScreen_screen_init(void)
{
    ui_bybyScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_bybyScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bybyScreen, lv_color_hex(0xA896C3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bybyScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bybyButton5 = lv_btn_create(ui_bybyScreen);
    lv_obj_set_width(ui_bybyButton5, 50);
    lv_obj_set_height(ui_bybyButton5, 50);
    lv_obj_set_x(ui_bybyButton5, 0);
    lv_obj_set_y(ui_bybyButton5, -24);
    lv_obj_set_align(ui_bybyButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bybyButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bybyButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bybyButton5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bybyButton5, lv_color_hex(0x6C80FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bybyButton5, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_bybyButton5);
    lv_obj_set_width(ui_Label16, 30);
    lv_obj_set_height(ui_Label16, 33);
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -1);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "\ue666");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x621E93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bybyPanel5 = lv_obj_create(ui_bybyScreen);
    lv_obj_set_width(ui_bybyPanel5, 200);
    lv_obj_set_height(ui_bybyPanel5, 20);
    lv_obj_set_x(ui_bybyPanel5, 4);
    lv_obj_set_y(ui_bybyPanel5, 56);
    lv_obj_set_align(ui_bybyPanel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bybyPanel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_bybyPanel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bybyPanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bybyPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bybyPanel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bybyPanel5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bybyPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_bybyPanel5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -3);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "正在关机，请等待");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bybyButton5, ui_event_bybyButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bybyScreen, ui_event_bybyScreen, LV_EVENT_ALL, NULL);

}

void ui_bybyScreen_screen_destroy(void)
{
    if(ui_bybyScreen) lv_obj_del(ui_bybyScreen);

    // NULL screen variables
    ui_bybyScreen = NULL;
    ui_bybyButton5 = NULL;
    ui_Label16 = NULL;
    ui_bybyPanel5 = NULL;
    ui_Label23 = NULL;

}