// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DATESCREEN_H
#define UI_DATESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DateScreen
extern void ui_DateScreen_screen_init(void);
extern void ui_DateScreen_screen_destroy(void);
extern void ui_event_DateScreen(lv_event_t * e);
extern lv_obj_t * ui_DateScreen;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_dateLabel4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

