// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HAND_H
#define UI_HAND_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Hand
extern void ui_Hand_screen_init(void);
extern void ui_Hand_screen_destroy(void);
extern void ui_event_Hand(lv_event_t * e);
extern lv_obj_t * ui_Hand;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

