// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_SizeScreen = NULL;
lv_obj_t * ui_datePanel2 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_SizePanel2 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_handPanel2 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_datePanel3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_SizeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_TScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_TScreen_screen_init);
    }
}

void ui_event_datePanel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_SizePanel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen8_screen_init);
    }
}

void ui_event_handPanel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Hand, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Hand_screen_init);
    }
}

void ui_event_datePanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DateScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DateScreen_screen_init);
    }
}

// build funtions

void ui_SizeScreen_screen_init(void)
{
    ui_SizeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SizeScreen, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_flex_flow(ui_SizeScreen, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_SizeScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SizeScreen, lv_color_hex(0x949194), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SizeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_SizeScreen, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SizeScreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_datePanel2 = lv_obj_create(ui_SizeScreen);
    lv_obj_set_width(ui_datePanel2, 230);
    lv_obj_set_height(ui_datePanel2, 40);
    lv_obj_set_x(ui_datePanel2, -5);
    lv_obj_set_y(ui_datePanel2, -63);
    lv_obj_set_align(ui_datePanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_datePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_datePanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_datePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_datePanel2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -97);
    lv_obj_set_y(ui_Label14, -1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "\u65e5\u671f"); // 日期
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_datePanel2);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -6);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "\u8ba1\u7b97\u5668");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SizePanel2 = lv_obj_create(ui_SizeScreen);
    lv_obj_set_width(ui_SizePanel2, 230);
    lv_obj_set_height(ui_SizePanel2, 40);
    lv_obj_set_x(ui_SizePanel2, -5);
    lv_obj_set_y(ui_SizePanel2, -63);
    lv_obj_set_align(ui_SizePanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SizePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_SizePanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SizePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_SizePanel2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -97);
    lv_obj_set_y(ui_Label20, -1);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "\u8bbe\u7f6e"); // 设置
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_SizePanel2);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -7);
    lv_obj_set_y(ui_Label18, -3);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "\u8bbe\u7f6e");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_huanzi30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_handPanel2 = lv_obj_create(ui_SizeScreen);
    lv_obj_set_width(ui_handPanel2, 230);
    lv_obj_set_height(ui_handPanel2, 40);
    lv_obj_set_x(ui_handPanel2, -3);
    lv_obj_set_y(ui_handPanel2, -53);
    lv_obj_set_align(ui_handPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_handPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_handPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_handPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_handPanel2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -97);
    lv_obj_set_y(ui_Label11, -1);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "\u5fc3\u8df3"); // 心跳
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_handPanel2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -7);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "\u5fc3\u8df3");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_huanzi30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datePanel3 = lv_obj_create(ui_SizeScreen);
    lv_obj_set_width(ui_datePanel3, 230);
    lv_obj_set_height(ui_datePanel3, 40);
    lv_obj_set_x(ui_datePanel3, -5);
    lv_obj_set_y(ui_datePanel3, -63);
    lv_obj_set_align(ui_datePanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_datePanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_datePanel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_datePanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_datePanel3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -97);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "\u65e5\u671f"); // 日期
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_datePanel3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -7);
    lv_obj_set_y(ui_Label4, 0);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "\u65e5\u671f");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_huanzi30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_datePanel2, ui_event_datePanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SizePanel2, ui_event_SizePanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_handPanel2, ui_event_handPanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_datePanel3, ui_event_datePanel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SizeScreen, ui_event_SizeScreen, LV_EVENT_ALL, NULL);

}

void ui_SizeScreen_screen_destroy(void)
{
    if(ui_SizeScreen) lv_obj_del(ui_SizeScreen);

    // NULL screen variables
    ui_SizeScreen = NULL;
    ui_datePanel2 = NULL;
    ui_Label14 = NULL;
    ui_Label24 = NULL;
    ui_SizePanel2 = NULL;
    ui_Label20 = NULL;
    ui_Label18 = NULL;
    ui_handPanel2 = NULL;
    ui_Label11 = NULL;
    ui_Label13 = NULL;
    ui_datePanel3 = NULL;
    ui_Label6 = NULL;
    ui_Label4 = NULL;

}