// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SIZESCREEN_H
#define UI_SIZESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SizeScreen
extern void ui_SizeScreen_screen_init(void);
extern void ui_SizeScreen_screen_destroy(void);
extern void ui_event_SizeScreen(lv_event_t * e);
extern lv_obj_t * ui_SizeScreen;
extern void ui_event_datePanel2(lv_event_t * e);
extern lv_obj_t * ui_datePanel2;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label24;
extern void ui_event_SizePanel2(lv_event_t * e);
extern lv_obj_t * ui_SizePanel2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label18;
extern void ui_event_handPanel2(lv_event_t * e);
extern lv_obj_t * ui_handPanel2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label13;
extern void ui_event_datePanel3(lv_event_t * e);
extern lv_obj_t * ui_datePanel3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

