// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_SIZE9;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_SIZE8;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_SIZE7;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_SIZE6;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_SIZE5;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_SIZE4;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_SIZE3;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_SIZE2;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_SIZE1;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

