// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../wifi_bluetooth_hardware.h"
#include "ui_TScreen.h"  // 包含 TScreen 头文件以访问 dropdown_visible

// Screen7 显示模式：0=WiFi模式，1=蓝牙模式
static int screen7_mode = 0;  // 0=WiFi, 1=Bluetooth

// WiFi和蓝牙状态
static bool wifi_enabled = false;
static bool bluetooth_enabled = false;
static char connected_wifi[32] = "";      // 已连接的WiFi名称
static char connected_bluetooth[32] = ""; // 已连接的蓝牙设备名称

// WiFi设备列表
typedef struct {
    lv_obj_t * panel;    // 面板对象
    lv_obj_t * icon;     // 图标
    lv_obj_t * name;     // 设备名称标签
} wifi_device_item_t;

static wifi_device_item_t wifi_devices[MAX_DEVICE_COUNT];
static int wifi_device_count = 0;

// 蓝牙设备列表
typedef struct {
    lv_obj_t * panel;    // 面板对象
    lv_obj_t * icon;     // 图标
    lv_obj_t * name;     // 设备名称标签
} bluetooth_device_item_t;

static bluetooth_device_item_t bluetooth_devices[MAX_DEVICE_COUNT];
static int bluetooth_device_count = 0;

// event functions 前向声明
static void ui_event_WiFiDeviceClick(lv_event_t * e);
static void ui_event_BluetoothDeviceClick(lv_event_t * e);

// 设备列表创建函数
void ui_create_wifi_device_item(const char *name);
void ui_create_bluetooth_device_item(const char *name);

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_WiFiPanel7 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_BluePanel7 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_blueXPanel7 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_wifeXPanel7 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label17 = NULL;
// event funtions
// 注意：ui_Container3, ui_WindosPane3, ui_BrighPanel3, ui_Label28, ui_Slider3,
//       ui_SizePanel3, ui_Label19, ui_BluePanel3, ui_Label38, ui_WiFiPanel3,
//       ui_Label39, ui_SutdownPanel3, ui_Label40, ui_TemPanel3, ui_Label41,
//       ui_clockPanel3, ui_Label42 这些是 TScreen 的下拉面板部件，
//       在 ui_Screen7.h 中声明为 extern，在 ui_TScreen.c 中定义

/**
 * WiFi开关事件回调
 */
static void ui_event_WiFiSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        wifi_enabled = lv_obj_has_state(ui_Switch2, LV_STATE_CHECKED);

        if(wifi_enabled) {
            // 打开WiFi：blueXPanel7背景变蓝色（blueXPanel7是WiFi开关面板）
            lv_obj_set_style_bg_color(ui_blueXPanel7, lv_color_hex(0x207864), LV_PART_MAIN | LV_STATE_DEFAULT);

            // 扫描并显示WiFi设备列表
            char device_names[MAX_DEVICE_COUNT][32];
            int count = 0;

            // 调用硬件接口扫描WiFi设备
            wifi_scan_devices(device_names, &count);

            wifi_device_count = 0;
            for(int i = 0; i < count && i < MAX_DEVICE_COUNT; i++) {
                ui_create_wifi_device_item(device_names[i]);
            }

            // 显示WiFi列表
            lv_obj_clear_flag(ui_WiFiPanel7, LV_OBJ_FLAG_HIDDEN);
        } else {
            // 关闭WiFi：恢复默认背景色，隐藏列表
            lv_obj_set_style_bg_color(ui_blueXPanel7, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_add_flag(ui_WiFiPanel7, LV_OBJ_FLAG_HIDDEN);

            // 断开连接
            if(connected_wifi[0] != '\0') {
                wifi_disconnect();
                connected_wifi[0] = '\0';
            }
        }
    }
}

/**
 * 蓝牙开关事件回调
 */
static void ui_event_BluetoothSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bluetooth_enabled = lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED);

        if(bluetooth_enabled) {
            // 打开蓝牙：wifeXPanel7背景变蓝色（wifeXPanel7是蓝牙开关面板）
            lv_obj_set_style_bg_color(ui_wifeXPanel7, lv_color_hex(0x207864), LV_PART_MAIN | LV_STATE_DEFAULT);

            // 扫描并显示蓝牙设备列表
            char device_names[MAX_DEVICE_COUNT][32];
            int count = 0;

            // 调用硬件接口扫描蓝牙设备
            bluetooth_scan_devices(device_names, &count);

            bluetooth_device_count = 0;
            for(int i = 0; i < count && i < MAX_DEVICE_COUNT; i++) {
                ui_create_bluetooth_device_item(device_names[i]);
            }

            // 显示蓝牙列表
            lv_obj_clear_flag(ui_BluePanel7, LV_OBJ_FLAG_HIDDEN);
        } else {
            // 关闭蓝牙：恢复默认背景色，隐藏列表
            lv_obj_set_style_bg_color(ui_wifeXPanel7, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_add_flag(ui_BluePanel7, LV_OBJ_FLAG_HIDDEN);

            // 断开连接
            if(connected_bluetooth[0] != '\0') {
                bluetooth_disconnect();
                connected_bluetooth[0] = '\0';
            }
        }
    }
}

/**
 * Screen7 手势事件：左滑返回上界面
 */
static void ui_event_Screen7_swipe(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT) {
            // 左滑返回 TScreen
            _ui_screen_change(&ui_TScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_TScreen_screen_init);
        // 恢复 TScreen 状态
            ui_TScreen_screen_resume();
        }
    }
}

/**
 * 创建WiFi设备列表项
 */
void ui_create_wifi_device_item(const char *name)
{
    if(wifi_device_count >= MAX_DEVICE_COUNT) return;

    // 创建设备面板
    lv_obj_t * panel = lv_obj_create(ui_WiFiPanel7);
    lv_obj_set_width(panel, 200);
    lv_obj_set_height(panel, 30);
    lv_obj_set_x(panel, 0);
    lv_obj_set_y(panel, 0);
    lv_obj_set_align(panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(panel, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(panel, lv_color_hex(0x9CA5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(panel, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建WiFi图标
    lv_obj_t * icon = lv_label_create(panel);
    lv_obj_set_width(icon, 30);
    lv_obj_set_height(icon, 30);
    lv_obj_set_x(icon, -85);
    lv_obj_set_y(icon, 0);
    lv_obj_set_align(icon, LV_ALIGN_CENTER);
    lv_label_set_text(icon, "\ue8c1");
    lv_obj_set_style_text_color(icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(icon, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建设备名称标签
    lv_obj_t * name_label = lv_label_create(panel);
    lv_obj_set_width(name_label, LV_SIZE_CONTENT);
    lv_obj_set_height(name_label, LV_SIZE_CONTENT);
    lv_obj_set_x(name_label, -20);
    lv_obj_set_y(name_label, 0);
    lv_obj_set_align(name_label, LV_ALIGN_CENTER);
    lv_label_set_text(name_label, name);
    lv_obj_set_style_text_color(name_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(name_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加点击事件回调
    lv_obj_add_event_cb(panel, ui_event_WiFiDeviceClick, LV_EVENT_CLICKED, (void*)name);

    // 检查是否是已连接的WiFi，如果是则设置蓝色背景
    if(strcmp(connected_wifi, name) == 0) {
        lv_obj_set_style_bg_color(panel, lv_color_hex(0x207864), LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // 保存到数组
    wifi_devices[wifi_device_count].panel = panel;
    wifi_devices[wifi_device_count].icon = icon;
    wifi_devices[wifi_device_count].name = name_label;
    wifi_device_count++;
}

/**
 * 创建蓝牙设备列表项
 */
void ui_create_bluetooth_device_item(const char *name)
{
    if(bluetooth_device_count >= MAX_DEVICE_COUNT) return;

    // 创建设备面板
    lv_obj_t * panel = lv_obj_create(ui_BluePanel7);
    lv_obj_set_width(panel, 200);
    lv_obj_set_height(panel, 30);
    lv_obj_set_x(panel, 0);
    lv_obj_set_y(panel, 0);
    lv_obj_set_align(panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(panel, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(panel, lv_color_hex(0x9CA5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(panel, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建蓝牙图标
    lv_obj_t * icon = lv_label_create(panel);
    lv_obj_set_width(icon, 30);
    lv_obj_set_height(icon, 30);
    lv_obj_set_x(icon, -85);
    lv_obj_set_y(icon, 0);
    lv_obj_set_align(icon, LV_ALIGN_CENTER);
    lv_label_set_text(icon, "\ue607");
    lv_obj_set_style_text_color(icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(icon, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建设备名称标签
    lv_obj_t * name_label = lv_label_create(panel);
    lv_obj_set_width(name_label, LV_SIZE_CONTENT);
    lv_obj_set_height(name_label, LV_SIZE_CONTENT);
    lv_obj_set_x(name_label, -20);
    lv_obj_set_y(name_label, 0);
    lv_obj_set_align(name_label, LV_ALIGN_CENTER);
    lv_label_set_text(name_label, name);
    lv_obj_set_style_text_color(name_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(name_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加点击事件回调
    lv_obj_add_event_cb(panel, ui_event_BluetoothDeviceClick, LV_EVENT_CLICKED, (void*)name);

    // 检查是否是已连接的蓝牙设备，如果是则设置蓝色背景
    if(strcmp(connected_bluetooth, name) == 0) {
        lv_obj_set_style_bg_color(panel, lv_color_hex(0x207864), LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // 保存到数组
    bluetooth_devices[bluetooth_device_count].panel = panel;
    bluetooth_devices[bluetooth_device_count].icon = icon;
    bluetooth_devices[bluetooth_device_count].name = name_label;
    bluetooth_device_count++;
}

/**
 * WiFi设备点击事件回调
 */
static void ui_event_WiFiDeviceClick(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        const char *wifi_name = (const char *)lv_event_get_user_data(e);

        // 调用硬件接口连接WiFi
        if(wifi_connect(wifi_name)) {
            // 连接成功，保存已连接的WiFi名称
            strcpy(connected_wifi, wifi_name);

            // 更新所有WiFi设备项的背景色
            for(int i = 0; i < wifi_device_count; i++) {
                const char *device_name = lv_label_get_text(wifi_devices[i].name);
                if(strcmp(device_name, wifi_name) == 0) {
                    // 已连接的WiFi设置蓝色背景
                    lv_obj_set_style_bg_color(wifi_devices[i].panel, lv_color_hex(0x207864), LV_PART_MAIN | LV_STATE_DEFAULT);
                } else {
                    // 其他WiFi设置默认背景色
                    lv_obj_set_style_bg_color(wifi_devices[i].panel, lv_color_hex(0x9CA5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
                }
            }
        }
    }
}

/**
 * 蓝牙设备点击事件回调
 */
static void ui_event_BluetoothDeviceClick(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        const char *device_name = (const char *)lv_event_get_user_data(e);

        // 调用硬件接口连接蓝牙设备
        if(bluetooth_connect(device_name)) {
            // 连接成功，保存已连接的蓝牙设备名称
            strcpy(connected_bluetooth, device_name);

            // 更新所有蓝牙设备项的背景色
            for(int i = 0; i < bluetooth_device_count; i++) {
                const char *dev_name = lv_label_get_text(bluetooth_devices[i].name);
                if(strcmp(dev_name, device_name) == 0) {
                    // 已连接的蓝牙设备设置蓝色背景
                    lv_obj_set_style_bg_color(bluetooth_devices[i].panel, lv_color_hex(0x207864), LV_PART_MAIN | LV_STATE_DEFAULT);
                } else {
                    // 其他蓝牙设备设置默认背景色
                    lv_obj_set_style_bg_color(bluetooth_devices[i].panel, lv_color_hex(0x9CA5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
                }
            }
        }
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    // 设置屏幕可滚动
    lv_obj_set_scroll_dir(ui_Screen7, LV_DIR_VER);  // 只允许垂直滚动
    // 添加左滑返回手势事件
    lv_obj_add_event_cb(ui_Screen7, ui_event_Screen7_swipe, LV_EVENT_GESTURE, NULL);

    // 重置下拉面板状态，确保返回主界面后可以正常下拉
    dropdown_visible = false;

    ui_WiFiPanel7 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_WiFiPanel7, 220);
    lv_obj_set_height(ui_WiFiPanel7, 200);
    lv_obj_set_x(ui_WiFiPanel7, -7);
    lv_obj_set_y(ui_WiFiPanel7, 80);  // 在开关下方
    lv_obj_set_align(ui_WiFiPanel7, LV_ALIGN_TOP_MID);
    // 允许滚动以显示设备列表
    lv_obj_set_scroll_dir(ui_WiFiPanel7, LV_DIR_VER);
    // 设置弹性布局，从上往下排列
    lv_obj_set_flex_flow(ui_WiFiPanel7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WiFiPanel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    // 初始隐藏WiFi列表
    lv_obj_add_flag(ui_WiFiPanel7, LV_OBJ_FLAG_HIDDEN);

    ui_Label32 = lv_label_create(ui_WiFiPanel7);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -81);
    lv_obj_set_y(ui_Label32, -1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "\ue8c1");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Label31 是空的标签，已删除

    ui_BluePanel7 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_BluePanel7, 220);
    lv_obj_set_height(ui_BluePanel7, 200);
    lv_obj_set_x(ui_BluePanel7, -14);
    lv_obj_set_y(ui_BluePanel7, 80);  // 在开关下方
    lv_obj_set_align(ui_BluePanel7, LV_ALIGN_TOP_MID);
    // 允许滚动以显示设备列表
    lv_obj_set_scroll_dir(ui_BluePanel7, LV_DIR_VER);
    // 设置弹性布局，从上往下排列
    lv_obj_set_flex_flow(ui_BluePanel7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BluePanel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    // 初始隐藏蓝牙列表
    lv_obj_add_flag(ui_BluePanel7, LV_OBJ_FLAG_HIDDEN);

    ui_Label34 = lv_label_create(ui_BluePanel7);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -81);
    lv_obj_set_y(ui_Label34, -1);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "\ue607");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueXPanel7 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_blueXPanel7, 200);
    lv_obj_set_height(ui_blueXPanel7, 50);
    lv_obj_set_x(ui_blueXPanel7, -2);
    lv_obj_set_y(ui_blueXPanel7, 20);  // 移到顶部
    lv_obj_set_align(ui_blueXPanel7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_blueXPanel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blueXPanel7, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueXPanel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_blueXPanel7);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 62);
    lv_obj_set_y(ui_Switch2, -2);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_TOP_MID);

    ui_Label2 = lv_label_create(ui_blueXPanel7);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "WiFi");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifeXPanel7 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_wifeXPanel7, 200);
    lv_obj_set_height(ui_wifeXPanel7, 50);
    lv_obj_set_x(ui_wifeXPanel7, -6);
    lv_obj_set_y(ui_wifeXPanel7, 20);  // 移到顶部
    lv_obj_set_align(ui_wifeXPanel7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_wifeXPanel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifeXPanel7, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifeXPanel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_wifeXPanel7);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 66);
    lv_obj_set_y(ui_Switch1, -2);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_TOP_MID);

    ui_Label17 = lv_label_create(ui_wifeXPanel7);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Blue");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加WiFi和蓝牙开关事件回调
    // ui_Switch1 是蓝牙开关（wifeXPanel7 中），绑定到蓝牙事件
    // ui_Switch2 是 WiFi 开关（blueXPanel7 中），绑定到 WiFi 事件
    lv_obj_add_event_cb(ui_Switch1, ui_event_BluetoothSwitch, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_WiFiSwitch, LV_EVENT_VALUE_CHANGED, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_WiFiPanel7 = NULL;
    ui_Label32 = NULL;
    ui_BluePanel7 = NULL;
    ui_Label34 = NULL;
    ui_blueXPanel7 = NULL;
    ui_Switch2 = NULL;
    ui_Label2 = NULL;
    ui_wifeXPanel7 = NULL;
    ui_Switch1 = NULL;
    ui_Label17 = NULL;
    // 注意：下拉面板变量（ui_Container3, ui_WindosPane3, ui_BrighPanel3, ui_Label28,
    //       ui_Slider3, ui_SizePanel3, ui_Label19, ui_BluePanel3, ui_Label38,
    //       ui_WiFiPanel3, ui_Label39, ui_SutdownPanel3, ui_Label40, ui_TemPanel3,
    //       ui_Label41, ui_clockPanel3, ui_Label42）由 TScreen 管理，不需要在此处理

}

/**
 * 设置 Screen7 显示模式
 * @param mode 0=WiFi模式, 1=蓝牙模式
 */
void ui_Screen7_set_mode(int mode)
{
    screen7_mode = mode;

    if(mode == 0) {
        // WiFi模式：显示WiFi相关部件（blueXPanel7是WiFi开关，Switch2是WiFi开关）
        if(ui_blueXPanel7) lv_obj_clear_flag(ui_blueXPanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_WiFiPanel7) lv_obj_clear_flag(ui_WiFiPanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_wifeXPanel7) lv_obj_add_flag(ui_wifeXPanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_BluePanel7) lv_obj_add_flag(ui_BluePanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_Switch1) lv_obj_add_flag(ui_Switch1, LV_OBJ_FLAG_HIDDEN);
    } else {
        // 蓝牙模式：显示蓝牙相关部件（wifeXPanel7是蓝牙开关，Switch1是蓝牙开关）
        if(ui_wifeXPanel7) lv_obj_clear_flag(ui_wifeXPanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_BluePanel7) lv_obj_clear_flag(ui_BluePanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_blueXPanel7) lv_obj_add_flag(ui_blueXPanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_WiFiPanel7) lv_obj_add_flag(ui_WiFiPanel7, LV_OBJ_FLAG_HIDDEN);
        if(ui_Switch2) lv_obj_add_flag(ui_Switch2, LV_OBJ_FLAG_HIDDEN);
    }
}