// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include <stdlib.h>  // 用于atof函数
#include <math.h>    // 用于floor函数

// 计算器状态变量
static char display_buffer[64] = "0"; // 显示缓冲区（字符串）
static double last_value = 0;         // 上一次输入的数值
static char last_operator = 0;        // 上一个运算符 (+, -, *, /)
static bool new_input = true;         // 是否开始新的输入

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label67 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label66 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label65 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label64 = NULL;
lv_obj_t * ui_SIZE9 = NULL;
lv_obj_t * ui_Label60 = NULL;
lv_obj_t * ui_SIZE8 = NULL;
lv_obj_t * ui_Label61 = NULL;
lv_obj_t * ui_SIZE7 = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label63 = NULL;
lv_obj_t * ui_SIZE6 = NULL;
lv_obj_t * ui_Label58 = NULL;
lv_obj_t * ui_SIZE5 = NULL;
lv_obj_t * ui_Label57 = NULL;
lv_obj_t * ui_SIZE4 = NULL;
lv_obj_t * ui_Label56 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Label62 = NULL;
lv_obj_t * ui_SIZE3 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_SIZE2 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_SIZE1 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label15 = NULL;
// event funtions

/**
 * 数字按钮事件回调：处理数字0-9的输入
 */
static void ui_event_number_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_t * btn = lv_event_get_target(e);
        lv_obj_t * label = lv_obj_get_child(btn, 0);
        const char * text = lv_label_get_text(label);

        // 获取输入的数字字符
        char digit = text[0];

        if(new_input) {
            // 新输入：清空缓冲区，设置第一个数字
            if(digit != '0') {
                display_buffer[0] = digit;
                display_buffer[1] = '\0';
                new_input = false;
            }
            // 如果是0，保持显示"0"
        } else {
            // 继续输入：追加数字（防止缓冲区溢出）
            size_t len = strlen(display_buffer);
            if(len < sizeof(display_buffer) - 1) {
                display_buffer[len] = digit;
                display_buffer[len + 1] = '\0';
            }
        }

        // 更新显示
        lv_label_set_text(ui_Label15, display_buffer);
    }
}

/**
 * 小数点按钮事件回调
 */
static void ui_event_decimal_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // 检查当前显示是否已包含小数点
        if(strchr(display_buffer, '.') == NULL) {
            // 没有小数点，添加小数点
            size_t len = strlen(display_buffer);
            if(len < sizeof(display_buffer) - 2) {
                display_buffer[len] = '.';
                display_buffer[len + 1] = '\0';
                lv_label_set_text(ui_Label15, display_buffer);
                new_input = false;
            }
        }
    }
}

/**
 * 运算符按钮事件回调：处理 +, -, *, /
 */
static void ui_event_operator_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // 从用户数据中获取运算符
        char op = (char)(intptr_t)lv_event_get_user_data(e);

        // 将当前显示的字符串转换为数值
        double current_val = atof(display_buffer);

        // 如果之前有运算符，先计算之前的表达式
        if(!new_input && last_operator != 0) {
            switch(last_operator) {
                case '+': last_value = last_value + current_val; break;
                case '-': last_value = last_value - current_val; break;
                case '*': last_value = last_value * current_val; break;
                case '/':
                    if(current_val != 0) {
                        last_value = last_value / current_val;
                    } else {
                        last_value = 0;
                    }
                    break;
            }
        } else {
            // 没有之前的运算，直接保存当前值
            last_value = current_val;
        }

        // 将结果转换为字符串（简单处理，最多10位数字）
        if(last_value >= -999999999.0 && last_value <= 999999999.0) {
            // 检查是否为整数
            double int_part;
            if(modf(last_value, &int_part) == 0.0) {
                lv_snprintf(display_buffer, sizeof(display_buffer), "%d", (int)last_value);
            } else {
                // 小数，最多显示3位
                lv_snprintf(display_buffer, sizeof(display_buffer), "%.3lf", last_value);
            }
        } else {
            lv_snprintf(display_buffer, sizeof(display_buffer), "error");
        }

        lv_label_set_text(ui_Label15, display_buffer);

        // 保存新的运算符，准备下一次输入
        last_operator = op;
        new_input = true;
    }
}

/**
 * 等号按钮事件回调：计算最终结果
 */
static void ui_event_equals_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // 将当前显示的字符串转换为数值
        double current_val = atof(display_buffer);

        // 执行之前保存的运算
        if(last_operator != 0) {
            switch(last_operator) {
                case '+': last_value = last_value + current_val; break;
                case '-': last_value = last_value - current_val; break;
                case '*': last_value = last_value * current_val; break;
                case '/':
                    if(current_val != 0) {
                        last_value = last_value / current_val;
                    } else {
                        last_value = 0;
                    }
                    break;
            }

            // 将结果转换为字符串（简单处理，最多10位数字）
            if(last_value >= -999999999.0 && last_value <= 999999999.0) {
                // 检查是否为整数
                double int_part;
                if(modf(last_value, &int_part) == 0.0) {
                    lv_snprintf(display_buffer, sizeof(display_buffer), "%d", (int)last_value);
                } else {
                    // 小数，最多显示3位
                    lv_snprintf(display_buffer, sizeof(display_buffer), "%.3lf", last_value);
                }
            } else {
                lv_snprintf(display_buffer, sizeof(display_buffer), "error");
            }

            lv_label_set_text(ui_Label15, display_buffer);
        }

        // 重置状态
        last_operator = 0;
        new_input = true;
    }
}

/**
 * 回退/删除按钮事件回调：删除最后一个字符
 */
static void ui_event_backspace_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        size_t len = strlen(display_buffer);

        if(len > 1) {
            // 删除最后一个字符
            display_buffer[len - 1] = '\0';
            lv_label_set_text(ui_Label15, display_buffer);
        } else if(len == 1) {
            // 只剩一个字符，删除后显示0
            strcpy(display_buffer, "0");
            lv_label_set_text(ui_Label15, "0");
            new_input = true;
        }
    }
}

void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SizeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SizeScreen_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xA4AEAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 240);
    lv_obj_set_height(ui_Container2, 200);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 39);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x201420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xA04A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 40);
    lv_obj_set_x(ui_Button1, -92);
    lv_obj_set_y(ui_Button1, -74);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "=");
    lv_obj_set_style_text_color(ui_Label67, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, -34);
    lv_obj_set_y(ui_Button3, -75);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button5, 50);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 27);
    lv_obj_set_y(ui_Button5, -73);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label66 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "/");
    lv_obj_set_style_text_color(ui_Label66, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label66, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button6, 50);
    lv_obj_set_height(ui_Button6, 40);
    lv_obj_set_x(ui_Button6, -88);
    lv_obj_set_y(ui_Button6, -29);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, ".");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button7, 50);
    lv_obj_set_height(ui_Button7, 40);
    lv_obj_set_x(ui_Button7, -32);
    lv_obj_set_y(ui_Button7, -29);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label64 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "*");
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE9 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE9, 50);
    lv_obj_set_height(ui_SIZE9, 40);
    lv_obj_set_x(ui_SIZE9, 36);
    lv_obj_set_y(ui_SIZE9, -21);
    lv_obj_set_align(ui_SIZE9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_SIZE9);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "9");
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE8 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE8, 50);
    lv_obj_set_height(ui_SIZE8, 40);
    lv_obj_set_x(ui_SIZE8, -92);
    lv_obj_set_y(ui_SIZE8, 19);
    lv_obj_set_align(ui_SIZE8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_SIZE8);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "8");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE7 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE7, 50);
    lv_obj_set_height(ui_SIZE7, 40);
    lv_obj_set_x(ui_SIZE7, -39);
    lv_obj_set_y(ui_SIZE7, 23);
    lv_obj_set_align(ui_SIZE7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_SIZE7);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "7");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button11, 50);
    lv_obj_set_height(ui_Button11, 40);
    lv_obj_set_x(ui_Button11, 35);
    lv_obj_set_y(ui_Button11, 23);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "-");
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE6 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE6, 50);
    lv_obj_set_height(ui_SIZE6, 40);
    lv_obj_set_x(ui_SIZE6, 89);
    lv_obj_set_y(ui_SIZE6, -70);
    lv_obj_set_align(ui_SIZE6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_SIZE6);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "6");
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE5 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE5, 50);
    lv_obj_set_height(ui_SIZE5, 40);
    lv_obj_set_x(ui_SIZE5, 94);
    lv_obj_set_y(ui_SIZE5, -23);
    lv_obj_set_align(ui_SIZE5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_SIZE5);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "5");
    lv_obj_set_style_text_color(ui_Label57, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE4 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE4, 50);
    lv_obj_set_height(ui_SIZE4, 40);
    lv_obj_set_x(ui_SIZE4, 80);
    lv_obj_set_y(ui_SIZE4, 25);
    lv_obj_set_align(ui_SIZE4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_SIZE4);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "4");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button15, 50);
    lv_obj_set_height(ui_Button15, 40);
    lv_obj_set_x(ui_Button15, -83);
    lv_obj_set_y(ui_Button15, 66);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "+");
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE3 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE3, 50);
    lv_obj_set_height(ui_SIZE3, 40);
    lv_obj_set_x(ui_SIZE3, -26);
    lv_obj_set_y(ui_SIZE3, 69);
    lv_obj_set_align(ui_SIZE3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_SIZE3);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "3");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE2 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE2, 50);
    lv_obj_set_height(ui_SIZE2, 40);
    lv_obj_set_x(ui_SIZE2, 36);
    lv_obj_set_y(ui_SIZE2, 64);
    lv_obj_set_align(ui_SIZE2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_SIZE2);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "2");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SIZE1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_SIZE1, 50);
    lv_obj_set_height(ui_SIZE1, 40);
    lv_obj_set_x(ui_SIZE1, -92);
    lv_obj_set_y(ui_SIZE1, -74);
    lv_obj_set_align(ui_SIZE1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SIZE1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SIZE1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SIZE1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SIZE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SIZE1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SIZE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_SIZE1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "1");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 240);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -88);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x744848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "0");  // 初始显示0

    // 为所有数字按钮添加事件回调
    lv_obj_add_event_cb(ui_SIZE1, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 1
    lv_obj_add_event_cb(ui_SIZE2, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 2
    lv_obj_add_event_cb(ui_SIZE3, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 3
    lv_obj_add_event_cb(ui_SIZE4, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 4
    lv_obj_add_event_cb(ui_SIZE5, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 5
    lv_obj_add_event_cb(ui_SIZE6, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 6
    lv_obj_add_event_cb(ui_SIZE7, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 7
    lv_obj_add_event_cb(ui_SIZE8, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 8
    lv_obj_add_event_cb(ui_SIZE9, ui_event_number_btn, LV_EVENT_CLICKED, NULL);   // 9

    // 为运算符按钮添加事件回调
    lv_obj_add_event_cb(ui_Button15, ui_event_operator_btn, LV_EVENT_CLICKED, (void*)'+');  // +
    lv_obj_add_event_cb(ui_Button11, ui_event_operator_btn, LV_EVENT_CLICKED, (void*)'-');  // -
    lv_obj_add_event_cb(ui_Button7,  ui_event_operator_btn, LV_EVENT_CLICKED, (void*)'*');  // *
    lv_obj_add_event_cb(ui_Button5,  ui_event_operator_btn, LV_EVENT_CLICKED, (void*)'/');  // /
    lv_obj_add_event_cb(ui_Button6,  ui_event_decimal_btn, LV_EVENT_CLICKED, NULL);    // .
    lv_obj_add_event_cb(ui_Button1,  ui_event_equals_btn, LV_EVENT_CLICKED, NULL);    // =
    lv_obj_add_event_cb(ui_Button3,  ui_event_backspace_btn, LV_EVENT_CLICKED, NULL);  // 回退按钮

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container2 = NULL;
    ui_Button1 = NULL;
    ui_Label67 = NULL;
    ui_Button3 = NULL;
    ui_Button5 = NULL;
    ui_Label66 = NULL;
    ui_Button6 = NULL;
    ui_Label65 = NULL;
    ui_Button7 = NULL;
    ui_Label64 = NULL;
    ui_SIZE9 = NULL;
    ui_Label60 = NULL;
    ui_SIZE8 = NULL;
    ui_Label61 = NULL;
    ui_SIZE7 = NULL;
    ui_Label59 = NULL;
    ui_Button11 = NULL;
    ui_Label63 = NULL;
    ui_SIZE6 = NULL;
    ui_Label58 = NULL;
    ui_SIZE5 = NULL;
    ui_Label57 = NULL;
    ui_SIZE4 = NULL;
    ui_Label56 = NULL;
    ui_Button15 = NULL;
    ui_Label62 = NULL;
    ui_SIZE3 = NULL;
    ui_Label55 = NULL;
    ui_SIZE2 = NULL;
    ui_Label44 = NULL;
    ui_SIZE1 = NULL;
    ui_Label21 = NULL;
    ui_Panel1 = NULL;
    ui_Label15 = NULL;

}
