// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TICK_H
#define UI_TICK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TICK
extern void ui_TICK_screen_init(void);
extern void ui_TICK_screen_destroy(void);
extern void ui_event_TICK(lv_event_t * e);
extern lv_obj_t * ui_TICK;
extern void timer_tick_cb(lv_timer_t * timer);  // 计时器回调函数声明
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label49;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
// CUSTOM VARIABLES
extern bool timer_running;           // 计时器是否运行
extern uint32_t timer_seconds;      // 已计时的秒数
extern lv_timer_t * timer_handle;   // LVGL定时器句柄

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

