// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TSCREEN_H
#define UI_TSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TScreen
extern void ui_TScreen_screen_init(void);
extern void ui_TScreen_screen_destroy(void);
extern lv_obj_t * ui_TScreen;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Spinner2;

// 下拉面板变量声明
extern lv_obj_t * ui_Container3;         // 下拉面板主容器
extern lv_obj_t * ui_WindosPane3;        // Windows面板
extern lv_obj_t * ui_BrighPanel3;        // 亮度面板
extern lv_obj_t * ui_Label28;            // 亮度标签
extern lv_obj_t * ui_Slider3;            // 亮度滑块
extern lv_obj_t * ui_SizePanel3;         // 尺寸面板
extern lv_obj_t * ui_Label19;            // 尺寸标签
extern lv_obj_t * ui_BluePanel3;         // 蓝牙面板
extern lv_obj_t * ui_Label38;            // 蓝牙标签
extern lv_obj_t * ui_WiFiPanel3;         // WiFi面板
extern lv_obj_t * ui_Label39;            // WiFi标签
extern lv_obj_t * ui_SutdownPanel3;       // 关机面板
extern lv_obj_t * ui_Label40;            // 关机标签
extern lv_obj_t * ui_TemPanel3;          // 温度面板
extern lv_obj_t * ui_Label41;            // 温度标签
extern lv_obj_t * ui_clockPanel3;        // 时钟面板
extern lv_obj_t * ui_Label42;            // 时钟标签

// 下拉面板状态标志
extern bool dropdown_visible;            // 下拉面板是否可见

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

