// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// Screen7 的声明已在 ui.h 中通过 #include "screens/ui_Screen7.h" 包含

// 下拉面板状态标志
bool dropdown_visible = false;  // 下拉面板是否可见

// 下拉面板变量（只在 TScreen 中定义和使用）
lv_obj_t * ui_Container3 = NULL;         // 下拉面板主容器
lv_obj_t * ui_WindosPane3 = NULL;        // Windows面板
lv_obj_t * ui_BrighPanel3 = NULL;        // 亮度面板
lv_obj_t * ui_Label28 = NULL;            // 亮度标签
lv_obj_t * ui_Slider3 = NULL;            // 亮度滑块
lv_obj_t * ui_SizePanel3 = NULL;         // 尺寸面板
lv_obj_t * ui_Label19 = NULL;            // 尺寸标签
lv_obj_t * ui_BluePanel3 = NULL;         // 蓝牙面板
lv_obj_t * ui_Label38 = NULL;            // 蓝牙标签
lv_obj_t * ui_WiFiPanel3 = NULL;         // WiFi面板
lv_obj_t * ui_Label39 = NULL;            // WiFi标签
lv_obj_t * ui_SutdownPanel3 = NULL;       // 关机面板
lv_obj_t * ui_Label40 = NULL;            // 关机标签
lv_obj_t * ui_TemPanel3 = NULL;          // 温度面板
lv_obj_t * ui_Label41 = NULL;            // 温度标签
lv_obj_t * ui_clockPanel3 = NULL;        // 时钟面板
lv_obj_t * ui_Label42 = NULL;            // 时钟标签

lv_obj_t * ui_TScreen = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_Spinner2 = NULL;

/**
 * 下拉面板事件回调：点击切换到SizeScreen
 */
static void ui_event_DropdownSizePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SizeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SizeScreen_screen_init);
    }
}

/**
 * 下拉面板事件回调：点击切换到bybyScreen
 */
static void ui_event_DropdownSutdownPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bybyScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_bybyScreen_screen_init);
    }
}

/**
 * 下拉面板事件回调：点击切换到TICK
 */
static void ui_event_DropdownClockPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TICK, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TICK_screen_init);
    }
}

/**
 * 下拉面板事件回调：点击切换到Screen7（WiFi和蓝牙界面）
 */
static void ui_event_DropdownWiFiPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // 强制隐藏下拉面板并重置状态
        if(ui_Container3 != NULL) {
            lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
        }
        if(ui_WindosPane3 != NULL) {
            lv_obj_add_flag(ui_WindosPane3, LV_OBJ_FLAG_HIDDEN);
        }
        dropdown_visible = false;

        // 跳转到 Screen7
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
        ui_Screen7_set_mode(0); // 设置为 WiFi 模式
    }
}

/**
 * 下拉面板事件回调：点击切换到Screen7（WiFi和蓝牙界面）
 */
static void ui_event_DropdownBluetoothPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // 强制隐藏下拉面板（包括 ui_Container3 和 ui_WindosPane3）
        if(ui_Container3 != NULL) {
            lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
        }
        if(ui_WindosPane3 != NULL) {
            lv_obj_add_flag(ui_WindosPane3, LV_OBJ_FLAG_HIDDEN);
        }
        // 跳转到 Screen7
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen7_screen_init);
        // 设置为蓝牙模式（在屏幕初始化后调用）
        ui_Screen7_set_mode(1);
    }
}

/**
 * 下拉面板事件回调：点击切换到尺寸设置界面
 */
void ui_event_SizePanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        if(ui_Container3 != NULL) {
            lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
        }
        _ui_screen_change(&ui_SizeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SizeScreen_screen_init);
    }
}

/**
 * 下拉面板事件回调：点击切换到关机界面
 */
void ui_event_SutdownPanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        if(ui_Container3 != NULL) {
            lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
        }
        _ui_screen_change(&ui_bybyScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_bybyScreen_screen_init);
    }
}

/**
 * 下拉面板事件回调：点击切换到计时器界面
 */
void ui_event_clockPanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        if(ui_Container3 != NULL) {
            lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
        }
        _ui_screen_change(&ui_TICK, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TICK_screen_init);
    }
}

/**
 * 动画完成回调：隐藏下拉面板
 */
static void hide_panel_anim_ready_cb(lv_anim_t * a)
{
    lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
}

/**
 * TScreen手势事件回调：处理下拉手势，控制Container3的显示/隐藏
 * Container3是TScreen的下拉面板组件，包含亮度、WiFi、蓝牙等快捷功能
 */
static void ui_TScreen_gesture_event(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);

    // 处理手势事件
    if(code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());

        // 向下滑动：显示下拉面板（Container3）
        if(dir == LV_DIR_BOTTOM) {
            if(!dropdown_visible) {
                dropdown_visible = true;
                // 初始Y位置为负值（准备从顶部滑入）
                lv_obj_set_y(ui_Container3, -140);
                // 清除隐藏标志
                lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
                if(ui_WindosPane3 != NULL) {
                    lv_obj_clear_flag(ui_WindosPane3, LV_OBJ_FLAG_HIDDEN);
                }
                lv_obj_set_style_opa(ui_Container3, 255, LV_PART_MAIN);
                // 将Container3移到最顶层，确保图标和文字可见
                lv_obj_move_foreground(ui_Container3);
                // 使用动画显示下拉面板，从顶部滑入
                lv_anim_t a;
                lv_anim_init(&a);
                lv_anim_set_var(&a, ui_Container3);
                lv_anim_set_values(&a, -140, 0);
                lv_anim_set_time(&a, 300);
                lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
                lv_anim_start(&a);
            }
        }
        // 向上滑动：隐藏下拉面板
        else if(dir == LV_DIR_TOP) {
            if(dropdown_visible) {
                dropdown_visible = false;
                // 使用动画隐藏下拉面板，向上滑出
                lv_anim_t a;
                lv_anim_init(&a);
                lv_anim_set_var(&a, ui_Container3);
                lv_anim_set_values(&a, 0, -140);
                lv_anim_set_time(&a, 300);
                lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
                lv_anim_set_ready_cb(&a, hide_panel_anim_ready_cb);
                lv_anim_start(&a);
            }
        }
    }
}

// build functions

/**
 * 返回 TScreen 时调用此函数，重置下拉面板状态
 */
void ui_TScreen_screen_resume(void)
{
    // 重置下拉面板状态
    dropdown_visible = false;
    if(ui_Container3 != NULL) {
        lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);
    }
    if(ui_WindosPane3 != NULL) {
        lv_obj_add_flag(ui_WindosPane3, LV_OBJ_FLAG_HIDDEN);
    }

    // 确保手势事件仍有效
    lv_obj_add_event_cb(ui_TScreen, ui_TScreen_gesture_event, LV_EVENT_GESTURE, NULL);
}

void ui_TScreen_screen_init(void)
{
    ui_TScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TScreen, lv_color_hex(0x949194), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加手势事件回调，用于显示/隐藏下拉面板
    lv_obj_add_event_cb(ui_TScreen, ui_TScreen_gesture_event, LV_EVENT_GESTURE, NULL);

    lv_obj_set_style_bg_color(ui_TScreen, lv_color_hex(0x949194), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TScreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // 创建下拉面板（Container3）及其子组件
    // Container3来自Screen7素材库，作为TScreen的下拉快捷功能面板
    ui_Container3 = lv_obj_create(ui_TScreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 240);
    lv_obj_set_height(ui_Container3, 140);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 0);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_HIDDEN);  // 初始隐藏

    ui_Label12 = lv_label_create(ui_TScreen);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -7);
    lv_obj_set_y(ui_Label12, -77);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "16:00"); //时间数据显示
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x1D4865), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_TScreen);
    lv_obj_set_width(ui_Panel17, 150);
    lv_obj_set_height(ui_Panel17, 30);
    lv_obj_set_x(ui_Panel17, -43);
    lv_obj_set_y(ui_Panel17, 30);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x706D70), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //湿度数据转换部件
    ui_Bar2 = lv_bar_create(ui_Panel17);
    lv_bar_set_value(ui_Bar2, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 50);
    lv_obj_set_height(ui_Bar2, 10);
    lv_obj_set_x(ui_Bar2, 41);
    lv_obj_set_y(ui_Bar2, -1);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -8);
    lv_obj_set_y(ui_Label22, -1);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "100%"); //湿度数据显示

    ui_Label25 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -53);
    lv_obj_set_y(ui_Label25, -1);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "\u6e7f\u5ea6");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xF8F4F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);
//心率部件
    ui_Panel2 = lv_obj_create(ui_TScreen);
    lv_obj_set_width(ui_Panel2, 150);
    lv_obj_set_height(ui_Panel2, 30);
    lv_obj_set_x(ui_Panel2, -43);
    lv_obj_set_y(ui_Panel2, 101);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x8A878A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 27);
    lv_obj_set_y(ui_Label35, 0);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "100");//心率数据显示

    ui_Label27 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -53);
    lv_obj_set_y(ui_Label27, -1);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "\u5fc3\u7387");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_TScreen);
    lv_obj_set_width(ui_Panel3, 150);
    lv_obj_set_height(ui_Panel3, 30);
    lv_obj_set_x(ui_Panel3, -43);
    lv_obj_set_y(ui_Panel3, 68);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x7B767B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 25);
    lv_obj_set_y(ui_Label36, 0);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "0°C");//温度数据显示

    ui_Label37 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -53);
    lv_obj_set_y(ui_Label37, -1);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "\u6e29\u5ea6");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_TScreen);
    lv_obj_set_width(ui_Panel18, 40);
    lv_obj_set_height(ui_Panel18, 150);
    lv_obj_set_x(ui_Panel18, 88);
    lv_obj_set_y(ui_Panel18, 41);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x7F7A7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label43, 30);
    lv_obj_set_height(ui_Label43, 60);
    lv_obj_set_x(ui_Label43, 6);
    lv_obj_set_y(ui_Label43, -41);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "\u4eca\u65e5\u6b65\u6570");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label45, 30);
    lv_obj_set_height(ui_Label45, 40);
    lv_obj_set_x(ui_Label45, 3);
    lv_obj_set_y(ui_Label45, 16);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "10000");//步数数据显示

    ui_Label46 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, -1);
    lv_obj_set_y(ui_Label46, 43);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "\u6b65");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_TScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -61);
    lv_obj_set_y(ui_Label1, -127);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "2026\u5e742\u670817\u65e5");//日期数据显示
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x1994DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_TScreen);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -78);
    lv_obj_set_y(ui_Label52, -6);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "\u65b9\u5411\uff1a106");
    lv_obj_set_style_text_font(ui_Label52, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_TScreen);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -72);
    lv_obj_set_y(ui_Label53, -34);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "\u6d77\u63a8\uff1a100\u7c73");
    lv_obj_set_style_text_font(ui_Label53, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_TScreen);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, 80);
    lv_obj_set_y(ui_Label54, -96);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "pm");//时间数据显示

    ui_Spinner2 = lv_spinner_create(ui_TScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 60);
    lv_obj_set_height(ui_Spinner2, 80);
    lv_obj_set_x(ui_Spinner2, 15);
    lv_obj_set_y(ui_Spinner2, -10);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner2, lv_color_hex(0x949194), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xAC95C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // 创建下拉面板的子组件（Container3已经在前面创建）
    ui_WindosPane3 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_WindosPane3, 240);
    lv_obj_set_height(ui_WindosPane3, 140);
    lv_obj_set_x(ui_WindosPane3, -2);
    lv_obj_set_y(ui_WindosPane3, -6);
    lv_obj_set_align(ui_WindosPane3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WindosPane3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_set_style_bg_color(ui_WindosPane3, lv_color_hex(0x9CA5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WindosPane3, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WindosPane3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrighPanel3 = lv_obj_create(ui_WindosPane3);
    lv_obj_set_width(ui_BrighPanel3, 230);
    lv_obj_set_height(ui_BrighPanel3, 40);
    lv_obj_set_x(ui_BrighPanel3, -4);
    lv_obj_set_y(ui_BrighPanel3, -46);
    lv_obj_set_align(ui_BrighPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrighPanel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_BrighPanel3, lv_color_hex(0x9CA5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrighPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrighPanel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrighPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_BrighPanel3);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label28, -97);
    lv_obj_set_y(ui_Label28, -1);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "\ue611");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_BrighPanel3);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 160);
    lv_obj_set_height(ui_Slider3, 20);
    lv_obj_set_x(ui_Slider3, 20);
    lv_obj_set_y(ui_Slider3, 0);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xEBE4FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xF6F6F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SizePanel3 = lv_obj_create(ui_WindosPane3);
    lv_obj_set_width(ui_SizePanel3, 40);
    lv_obj_set_height(ui_SizePanel3, 35);
    lv_obj_set_x(ui_SizePanel3, -15);
    lv_obj_set_y(ui_SizePanel3, 0);
    lv_obj_set_align(ui_SizePanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SizePanel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_SizePanel3, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SizePanel3, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SizePanel3, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SizePanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SizePanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_SizePanel3, LV_OBJ_FLAG_CLICKABLE);

    ui_Label19 = lv_label_create(ui_SizePanel3);
    lv_obj_set_width(ui_Label19, 39);
    lv_obj_set_height(ui_Label19, 35);
    lv_obj_set_x(ui_Label19, 1);
    lv_obj_set_y(ui_Label19, 0);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "\ue643");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BluePanel3 = lv_obj_create(ui_WindosPane3);
    lv_obj_set_width(ui_BluePanel3, 40);
    lv_obj_set_height(ui_BluePanel3, 35);
    lv_obj_set_x(ui_BluePanel3, -89);
    lv_obj_set_y(ui_BluePanel3, -2);
    lv_obj_set_align(ui_BluePanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BluePanel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_BluePanel3, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluePanel3, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BluePanel3, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BluePanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BluePanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_BluePanel3, LV_OBJ_FLAG_CLICKABLE);

    ui_Label38 = lv_label_create(ui_BluePanel3);
    lv_obj_set_width(ui_Label38, 30);
    lv_obj_set_height(ui_Label38, 35);
    lv_obj_set_x(ui_Label38, -3);
    lv_obj_set_y(ui_Label38, 3);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "\ue607");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiPanel3 = lv_obj_create(ui_WindosPane3);
    lv_obj_set_width(ui_WiFiPanel3, 40);
    lv_obj_set_height(ui_WiFiPanel3, 35);
    lv_obj_set_x(ui_WiFiPanel3, -88);
    lv_obj_set_y(ui_WiFiPanel3, 41);
    lv_obj_set_align(ui_WiFiPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WiFiPanel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_WiFiPanel3, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiPanel3, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WiFiPanel3, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WiFiPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WiFiPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_WiFiPanel3, LV_OBJ_FLAG_CLICKABLE);

    ui_Label39 = lv_label_create(ui_WiFiPanel3);
    lv_obj_set_width(ui_Label39, 30);
    lv_obj_set_height(ui_Label39, 35);
    lv_obj_set_x(ui_Label39, 0);
    lv_obj_set_y(ui_Label39, 3);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "\ue8c1");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SutdownPanel3 = lv_obj_create(ui_WindosPane3);
    lv_obj_set_width(ui_SutdownPanel3, 40);
    lv_obj_set_height(ui_SutdownPanel3, 35);
    lv_obj_set_x(ui_SutdownPanel3, 68);
    lv_obj_set_y(ui_SutdownPanel3, 44);
    lv_obj_set_align(ui_SutdownPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SutdownPanel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_SutdownPanel3, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SutdownPanel3, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SutdownPanel3, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SutdownPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SutdownPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_SutdownPanel3, LV_OBJ_FLAG_CLICKABLE);

    ui_Label40 = lv_label_create(ui_SutdownPanel3);
    lv_obj_set_width(ui_Label40, 40);
    lv_obj_set_height(ui_Label40, 35);
    lv_obj_set_x(ui_Label40, 2);
    lv_obj_set_y(ui_Label40, 3);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "\ue666");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemPanel3 = lv_obj_create(ui_WindosPane3);
    lv_obj_set_width(ui_TemPanel3, 40);
    lv_obj_set_height(ui_TemPanel3, 35);
    lv_obj_set_x(ui_TemPanel3, 66);
    lv_obj_set_y(ui_TemPanel3, -2);
    lv_obj_set_align(ui_TemPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TemPanel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_TemPanel3, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemPanel3, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemPanel3, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TemPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_TemPanel3, LV_OBJ_FLAG_CLICKABLE);

    ui_Label41 = lv_label_create(ui_TemPanel3);
    lv_obj_set_width(ui_Label41, 30);
    lv_obj_set_height(ui_Label41, 35);
    lv_obj_set_x(ui_Label41, -5);
    lv_obj_set_y(ui_Label41, 1);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "\ue6bd");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_ionc32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockPanel3 = lv_obj_create(ui_WindosPane3);
    lv_obj_set_width(ui_clockPanel3, 40);
    lv_obj_set_height(ui_clockPanel3, 35);
    lv_obj_set_x(ui_clockPanel3, -16);
    lv_obj_set_y(ui_clockPanel3, 43);
    lv_obj_set_align(ui_clockPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clockPanel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_clockPanel3, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clockPanel3, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clockPanel3, lv_color_hex(0x2E3130), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clockPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_clockPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_clockPanel3, LV_OBJ_FLAG_CLICKABLE);

    ui_Label42 = lv_label_create(ui_clockPanel3);
    lv_obj_set_width(ui_Label42, 30);
    lv_obj_set_height(ui_Label42, 35);
    lv_obj_set_x(ui_Label42, 0);
    lv_obj_set_y(ui_Label42, 5);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "\ue672");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_part, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加下拉面板中的按钮事件回调
    lv_obj_add_event_cb(ui_SizePanel3, ui_event_DropdownSizePanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SutdownPanel3, ui_event_DropdownSutdownPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clockPanel3, ui_event_DropdownClockPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiPanel3, ui_event_DropdownWiFiPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BluePanel3, ui_event_DropdownBluetoothPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TScreen, ui_TScreen_gesture_event, LV_EVENT_GESTURE, NULL);
}

void ui_TScreen_screen_destroy(void)
{
    if(ui_TScreen) lv_obj_del(ui_TScreen);

    // NULL screen variables
    ui_TScreen = NULL;
    ui_Label12 = NULL;
    ui_Panel17 = NULL;
    ui_Bar2 = NULL;
    ui_Label22 = NULL;
    ui_Label25 = NULL;
    ui_Panel2 = NULL;
    ui_Label35 = NULL;
    ui_Label27 = NULL;
    ui_Panel3 = NULL;
    ui_Label36 = NULL;
    ui_Label37 = NULL;
    ui_Panel18 = NULL;
    ui_Label43 = NULL;
    ui_Label45 = NULL;
    ui_Label46 = NULL;
    ui_Label1 = NULL;
    ui_Label52 = NULL;
    ui_Label53 = NULL;
    ui_Label54 = NULL;
    ui_Spinner2 = NULL;

    // NULL 下拉面板变量
    ui_Container3 = NULL;
    ui_WindosPane3 = NULL;
    ui_BrighPanel3 = NULL;
    ui_Label28 = NULL;
    ui_Slider3 = NULL;
    ui_SizePanel3 = NULL;
    ui_Label19 = NULL;
    ui_BluePanel3 = NULL;
    ui_Label38 = NULL;
    ui_WiFiPanel3 = NULL;
    ui_Label39 = NULL;
    ui_SutdownPanel3 = NULL;
    ui_Label40 = NULL;
    ui_TemPanel3 = NULL;
    ui_Label41 = NULL;
    ui_clockPanel3 = NULL;
    ui_Label42 = NULL;
}