// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// 计时器状态变量（非static，以便在ui_events.c中访问）
bool timer_running = false;                // 计时器是否运行
uint32_t timer_seconds = 0;               // 已计时的秒数
lv_timer_t * timer_handle = NULL;          // LVGL定时器句柄

// 默认按钮颜色
#define BUTTON_COLOR_NORMAL   0x207864
// 结束按钮颜色（红色）
#define BUTTON_COLOR_STOP     0xFF0000

lv_obj_t * ui_TICK = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_Label51 = NULL;
// event funtions

/**
 * 计时器回调函数：每1000ms调用一次，更新计时显示
 * 必须是非static函数，因为需要在外部文件(ui_events.c)中调用lv_timer_create
 */
void timer_tick_cb(lv_timer_t * timer)
{
    timer_seconds++;

    // 计算小时、分钟、秒
    uint32_t hours = timer_seconds / 3600;
    uint32_t minutes = (timer_seconds % 3600) / 60;
    uint32_t seconds = timer_seconds % 60;

    // 格式化时间字符串为 HH:MM:SS
    char time_str[16];
    lv_snprintf(time_str, sizeof(time_str), "%02d:%02d:%02d", hours, minutes, seconds);

    // 更新计时显示标签
    lv_label_set_text(ui_Label49, time_str);
}

void ui_event_TICK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_TScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TScreen_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        TickStart(e);
    }
}

// build funtions

void ui_TICK_screen_init(void)
{
    ui_TICK = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TICK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TICK, lv_color_hex(0x201420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TICK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_TICK);
    lv_obj_set_width(ui_Panel19, 150);
    lv_obj_set_height(ui_Panel19, 150);
    lv_obj_set_x(ui_Panel19, 2);
    lv_obj_set_y(ui_Panel19, -48);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x3574D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "00:00:00");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x000302), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_TICK);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 3);
    lv_obj_set_y(ui_Button4, 73);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x207864), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 2);
    lv_obj_set_y(ui_Label26, 1);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "\u5f00\u59cb");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_TICK);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -56);
    lv_obj_set_y(ui_Label50, 115);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "\u5f00\u59cb\u8ba1\u6570");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_TICK);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 57);
    lv_obj_set_y(ui_Label51, 113);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "\u7ed3\u675f\u8ba1\u6570");
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &ui_font_tianqhuanzi16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TICK, ui_event_TICK, LV_EVENT_ALL, NULL);

}

void ui_TICK_screen_destroy(void)
{
    // 如果定时器还在运行，先删除定时器
    if(timer_handle != NULL) {
        lv_timer_del(timer_handle);
        timer_handle = NULL;
    }

    if(ui_TICK) lv_obj_del(ui_TICK);

    // 重置计时器状态
    timer_running = false;
    timer_seconds = 0;

    // NULL screen variables
    ui_TICK = NULL;
    ui_Panel19 = NULL;
    ui_Label49 = NULL;
    ui_Button4 = NULL;
    ui_Label26 = NULL;
    ui_Label50 = NULL;
    ui_Label51 = NULL;

}