// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_WeclomeScreen = NULL;
lv_obj_t * ui_WeclomeLabel1 = NULL;

// event funtions
/**
 * 定时器回调函数：2秒后自动切换到TScreen界面
 * @param timer 定时器对象
 */
static void weclomescreen_timer_cb(lv_timer_t * timer)
{
    // 删除定时器，避免重复执行
    lv_timer_del(timer);
    // 初始化TScreen界面
    ui_TScreen_screen_init();
    // 加载TScreen界面作为当前屏幕
    lv_scr_load(ui_TScreen);
    // 销毁WeclomeScreen界面，释放资源
    ui_WeclomeScreen_screen_destroy();
}

// build funtions

void ui_WeclomeScreen_screen_init(void)
{
    ui_WeclomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeclomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeclomeScreen, lv_color_hex(0x2BCED5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeclomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeclomeLabel1 = lv_label_create(ui_WeclomeScreen);
    lv_obj_set_width(ui_WeclomeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeclomeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeclomeLabel1, -2);
    lv_obj_set_y(ui_WeclomeLabel1, -30);
    lv_obj_set_align(ui_WeclomeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeclomeLabel1, "you're welcome");
    lv_obj_set_style_text_color(ui_WeclomeLabel1, lv_color_hex(0xCDC7D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeclomeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeclomeLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_timer_create(weclomescreen_timer_cb, 2000, NULL);
}

void ui_WeclomeScreen_screen_destroy(void)
{
    if(ui_WeclomeScreen) lv_obj_del(ui_WeclomeScreen);

    // NULL screen variables
    ui_WeclomeScreen = NULL;
    ui_WeclomeLabel1 = NULL;

}
