// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_WECLOMESCREEN_H
#define UI_WECLOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeclomeScreen
extern void ui_WeclomeScreen_screen_init(void);
extern void ui_WeclomeScreen_screen_destroy(void);
extern lv_obj_t * ui_WeclomeScreen;
extern lv_obj_t * ui_WeclomeLabel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

