// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_WeclomeScreen.h"
#include "screens/ui_SizeScreen.h"
#include "screens/ui_TScreen.h"
#include "screens/ui_DateScreen.h"
#include "screens/ui_bybyScreen.h"
#include "screens/ui_Hand.h"
#include "screens/ui_Screen7.h"  // WiFi和蓝牙界面
#include "screens/ui_TICK.h"
#include "screens/ui_Screen8.h"
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_ALIBABAB6);
LV_FONT_DECLARE(ui_font_huanzi30);
LV_FONT_DECLARE(ui_font_ionc32);
LV_FONT_DECLARE(ui_font_part);
LV_FONT_DECLARE(ui_font_tianqhuanzi16);
LV_FONT_DECLARE(ui_font_ALliBABA16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
