// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void Dalaytime(lv_event_t * e)
{
	// Your code here
}
// 关机函数
void Shutdown(lv_event_t * e)
{
	// Your code here
}

// 外部引用TICK界面的变量
extern lv_obj_t * ui_Label26;   // 按钮上的文字标签
extern lv_obj_t * ui_Button4;   // 按钮
extern lv_obj_t * ui_Label49;   // 计时显示标签

void TickStart(lv_event_t * e)
{
    // 计时器运行状态变量（定义在ui_TICK.c中）
    extern bool timer_running;
    extern uint32_t timer_seconds;
    extern lv_timer_t * timer_handle;

    // 结束按钮颜色（红色）
    #define BUTTON_COLOR_STOP     0xFF0000
    // 开始按钮颜色（默认）
    #define BUTTON_COLOR_NORMAL   0x207864

    if(timer_running == false) {
        // 当前状态：停止 -> 开始计时
        timer_running = true;

        // 更新按钮文本为"结束"
        lv_label_set_text(ui_Label26, "\u7ed3\u675f");

        // 更新按钮颜色为红色
        lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(BUTTON_COLOR_STOP), LV_PART_MAIN | LV_STATE_DEFAULT);

        // 创建并启动定时器，每1000ms（1秒）调用一次timer_tick_cb
        if(timer_handle == NULL) {
            timer_handle = lv_timer_create(timer_tick_cb, 1000, NULL);
        } else {
            lv_timer_resume(timer_handle);
        }
    } else {
        // 当前状态：运行 -> 停止计时
        timer_running = false;

        // 更新按钮文本为"开始"
        lv_label_set_text(ui_Label26, "\u5f00\u59cb");

        // 恢复按钮默认颜色
        lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(BUTTON_COLOR_NORMAL), LV_PART_MAIN | LV_STATE_DEFAULT);

        // 暂停定时器
        if(timer_handle != NULL) {
            lv_timer_pause(timer_handle);
        }

        // 注意：保持当前计时时间不变，等待下次点击"开始"继续计时
    }
}